[package]
name = "my-dapp"
version = "1.0.0"
authors = []

[addresses]
mydapp_addr = "1c578cac40ddda1ec3fa08f3d0349b36c1997ea21531011bea332e4901f0e667"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
