version: '3.8'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil"]
    command: ["--block-time", "10"]
    ports:
      - "8545:8545"
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    working_dir: /anvil
    volumes:
      - anvil-data:/data
    networks:
      - mev-network

  deployer:
    build:
      context: .
      dockerfile: docker/deployer.Dockerfile
    volumes:
      - ./shared:/shared
    environment:
      - ANVIL_URL=http://anvil:8545
      - PRIVATE_KEY_DEPLOYER=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    networks:
      - mev-network

  game-manager:
    build:
      context: .
      dockerfile: docker/game-manager.Dockerfile
    volumes:
      - ./src:/app/src
      - ./shared:/shared
    environment:
      - ANVIL_URL=http://anvil:8545
    networks:
      - mev-network

  caller-bot:
    build:
      context: .
      dockerfile: docker/caller-bot.Dockerfile
    volumes:
      - ./src:/app/src
      - ./shared:/shared
    environment:
      - ANVIL_URL=http://anvil:8545
    networks:
      - mev-network

networks:
  mev-network:
    driver: bridge

volumes:
  anvil-data: 